[package]
name = "clabby"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "clabby"
path = "src/main.rs"

[dependencies]
clabby-core = { path = "../core", version = "0.1.0" }
tokio = { workspace = true }
clap = { version = "4", features = ["derive"] }
anyhow = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio-cron-scheduler = "0.15.1"
serde_json = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
assert_cmd = "2.2.2"
assert_fs = "1.1.4"
predicates = "3.1.4"
trycmd = "1.2.0"
